lib/uspol_web/router.ex
defmodule UspolWeb.Router do
  use UspolWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Uspol.Plugs.SetUser
  end

  pipeline :auth do
    plug UspolWeb.Plugs.RequireAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UspolWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create, :delete]
  end

  scope "/", UspolWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/videos", VideoController, only: [:index, :show]

  end

  scope "/auth", UspolWeb do
    pipe_through :browser

    # using :provider instead of google, can use the same route for any authentication solution
    get "/signout", SessionController, :delete
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :create
  end
end

lib/uspol_web/views/layout_view.ex
defmodule UspolWeb.LayoutView do
  use UspolWeb, :view
end

lib/uspol_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Uspol · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "nav.html", conn: @conn %>
    <main role="main">
      <p class="alert bg-blue-lightest border border-blue-light text-blue-dark px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert bg-red-lightest border border-red-light text-red-dark px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/uspol_web/templates/layout/nav.html.eex
<nav class="flex items-center justify-between flex-wrap bg-grey p-3 font-sans">
  <div class="flex items-center flex-no-shrink text-grey-darkest mr-6">
    <span class="font-semibold text-xl tracking-tight">US Politics</span>
  </div>
  <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="nav">
    <div class="text-sm lg:flex-grow">
    </div>
    <div>

      <%= if @conn.assigns[:user] do %>
        <span class="block mt-4 lg:inline-block lg:mt-0 text-blue mr-4 no-underline">
          Signed in as <%= @conn.assigns.user.first_name %>.
        </span>

        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline" %>
        <%= link "Add video", to: Routes.video_path(@conn, :new), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline" %>
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline" %>
      <% else %>
        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline" %>
        <a href="/auth/google?scope=email%20profile" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline">
          Sign in with Google
        </a>
      <% end %>


    </div>
  </div>
</nav>